ALTER TABLE restaurants ADD COLUMN created TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT timezone('UTC', now());
ALTER TABLE restaurants ADD COLUMN updated TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE restaurants ALTER COLUMN created DROP DEFAULT;

